// Sample backup jobs for the demo. Shape mirrors hozo.config.models.JobConfig
// + the JobResult fields the dashboard reads. Three jobs cover the three
// states the UI distinguishes: green, error, never-run.

const now = Date.now();
const HOUR = 3600 * 1000;
const DAY = 24 * HOUR;

module.exports = [
  {
    name: "nightly-rpool",
    description: "Nightly snapshot of root pool to offsite NUC",
    source: "rpool/data",
    source_dataset: "rpool/data",
    target_host: "backup-box.tailnet.ts.net",
    target_dataset: "backup/rpool-data",
    mac_address: "AA:BB:CC:DD:EE:FF",
    schedule: "daily 02:30",
    ssh_user: "root",
    ssh_port: 22,
    ssh_key: "~/.ssh/id_ed25519",
    timeout: 120,
    retries: 3,
    retry_delay: 60,
    wol_broadcast: "255.255.255.255",
    recursive: true,
    shutdown_after: true,
    no_privilege_elevation: false,
    backup_device: "/dev/sdb",
    disk_spinup_timeout: 90,
    last_result: {
      success: true,
      started_at: new Date(now - 8 * HOUR).toISOString(),
      finished_at: new Date(now - 8 * HOUR + 412 * 1000).toISOString(),
      duration_seconds: 412.3,
      attempts: 1,
      snapshots_after_count: 47,
      error: null,
    },
  },
  {
    name: "weekly-photos",
    description: "Weekly archive of irreplaceable photo library",
    source: "tank/photos",
    source_dataset: "tank/photos",
    target_host: "backup-box.tailnet.ts.net",
    target_dataset: "backup/photos",
    mac_address: "AA:BB:CC:DD:EE:FF",
    schedule: "weekly Sunday 03:00",
    ssh_user: "root",
    ssh_port: 22,
    ssh_key: "~/.ssh/id_ed25519",
    timeout: 120,
    retries: 3,
    retry_delay: 60,
    wol_broadcast: "255.255.255.255",
    recursive: true,
    shutdown_after: true,
    no_privilege_elevation: false,
    backup_device: "/dev/sdb",
    disk_spinup_timeout: 90,
    last_result: {
      success: false,
      started_at: new Date(now - 2 * DAY).toISOString(),
      finished_at: new Date(now - 2 * DAY + 89 * 1000).toISOString(),
      duration_seconds: 89.2,
      attempts: 3,
      snapshots_after_count: 12,
      error: "syncoid: cannot receive incremental stream: most recent snapshot does not match incremental source",
    },
  },
  {
    name: "monthly-archive",
    description: "Monthly snapshot of the writing archive",
    source: "tank/archive",
    source_dataset: "tank/archive",
    target_host: "backup-box.tailnet.ts.net",
    target_dataset: "backup/archive",
    mac_address: "AA:BB:CC:DD:EE:FF",
    schedule: "",
    ssh_user: "root",
    ssh_port: 22,
    ssh_key: "~/.ssh/id_ed25519",
    timeout: 120,
    retries: 3,
    retry_delay: 60,
    wol_broadcast: "255.255.255.255",
    recursive: false,
    shutdown_after: true,
    no_privilege_elevation: false,
    backup_device: "",
    disk_spinup_timeout: 90,
    last_result: null,
  },
];
